networks:
  ai_network:
    driver: bridge

services:
  wan2.1:
    image: wan2.1:1.0
    container_name: wan2.1
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/Wan2.1/results:/code/results
      - d:/AI/Wan2.1/error:/code/error
      - d:/AI/Wan2.1/logs:/code/logs
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    shm_size: '32g'
    networks:
      - ai_network
